#!/bin/bash

case "$1" in
    "local")
        docker run --rm -it -p 4000:4000 -v $(pwd):/app -w /app --name inf19bot inf19bot

        #cd api
        #php -S localhost:4000
        ;;
    "check")
        php run.php -- $2
        ;;
    "cmd")
        REQUEST=$(sed "s/<cmd>/$2/g" ./request)
        curl localhost:4000/hook.php \
            --data "$REQUEST"
        ;;
    *)
        echo "no command given or not a command. use:"
        echo "local, check, cmd"
        ;;
esac

